name: 'Convert JSON to CSV'
description: 'Converts a JSON file to CSV format'
author: 'doapply'
inputs:
  json_file:
    description: 'The JSON file to convert'
    required: true
outputs:
  csv_file:
    description: 'The resulting CSV file'
